#!/bin/bash

# Sends error messages to Honeybadger. Expects a template json body to
# send errors. Options are the template values. 
#
# This script and template is made for logrotate error notifications.

echoerr() { 
  echo "$@" 1>&2 
}

usage() {
  echoerr "Usage: $0 -m \"ERROR_MESSAGE\" -e ENVIRONMENT -h HOSTNAME"
  exit 1
}

# Adds two backslash to a double-quote for awk-substituted JSON values
# " => \\"
double_escape_double_quote() {
  echo ${@//\"/\\\\\"}
}

while getopts ":m:e:h:" optname; do
  case "$optname" in 
    "m")
      error_message=$(double_escape_double_quote "$OPTARG")
     ;;
    "e")
      environment=$OPTARG
      case "$environment" in  
        production)
          ;;
        sandbox)
          ;;
        test)
          ;;
        *)
          echo "Uknown environment $environment."
          usage
          ;;
      esac
      ;;
    "h")
      hostname=$(double_escape_double_quote "$OPTARG")
      ;;
    *)
      # Should not happen
      echoerr "Uknown option $optname."
      usage
      ;;
  esac
done 

# Exit if required options are missing
if [ -z "$error_message" ]; then echoerr "Error message option -m is required."; usage; fi
if [ -z "$environment" ]; then echoerr "Environment option -e is required."; usage; fi
if [ -z "$hostname" ]; then echoerr "Hostname option -h is required."; usage; fi

error_template=/home/ec2-user/honeybadger_template.json
error_message_body=/home/ec2-user/honeybadger_error.json
old_error_message_body=/home/ec2-user/honeybadger_error_old.json
honeybadger_api_key=REMOVED

awk -v MESSAGE="$error_message" -v ENVIRONMENT="$environment" -v HOSTNAME="$hostname" '{
  sub(/MESSAGE/, MESSAGE);
  sub(/ENVIRONMENT/, ENVIRONMENT);
  sub(/HOSTNAME/, HOSTNAME);
  print;
}' $error_template > $error_message_body

curl --silent -X POST \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -H "X-API-Key: $honeybadger_api_key" \
     --data-binary @/$error_message_body \
     https://api.honeybadger.io/v1/notices

mv $error_message_body $old_error_message_body
