#!/bin/bash

# Tries multiple times to put a file onto an s3 location. The error response file
# can be checked for any errors from the AWS S3 request.

echoerr() { 
  echo "$@" 1>&2 
}

usage() {
  echoerr "Usage: $0 -s SOURCE_FILE_PATTERN -d DESTIATION_S3_BUCKET_OBJECT -e ERROR_RESPONSE_FILE"
  exit 1
}

while getopts ":s:d:e:" optname; do
  case "$optname" in 
    "s")
      s3_source="$OPTARG"
      number_matching_files=$(stat -t $s3_source 2>/dev/null | wc -l)
      if [ $number_matching_files -ne 1 ]; then
        echoerr "The pattern $s3_source must match exactly 1 file. Found $number_matching_files matches."
        usage
      fi
      ;;
    "d")
      s3_destination="$OPTARG"
      ;;
    "e")
      s3_error="$OPTARG"
      ;;
    *)
      # Should not happen
      echoerr "Uknown option."
      usage
      ;;
  esac
done

# Exit if required options are missing
if [ -z "$s3_source" ]; then echoerr "Source option -s is required."; usage; fi
if [ -z "$s3_destination" ]; then echoerr "Destination option -d is required."; usage; fi
if [ -z "$s3_error" ]; then echoerr "Error file option -e is required."; usage; fi

return_code=1
tries=1

while [ $tries -le 3 ] && [ $return_code -ne 0 ]; do
  aws s3 cp --region us-east-1 $s3_source s3://"$s3_destination"
  return_code=$?
  sleep $(( $tries * 5 ))
  tries=$(( $tries + 1 ))
done
rm $s3_source

exit $return_code
